# syntax=docker/dockerfile:1

ARG NODE_VERSION=20.11.1

# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base

# Set working directory for all build stages.
WORKDIR /usr/src/app

# Create a stage for installing dependencies.
FROM base as deps

# Copy package.json and package-lock.json for dependency installation.
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source files into the image.
COPY . .

# Expose the port that the application listens on.
EXPOSE 5173

# Run the application in development mode.
CMD ["npm", "run", "dev"]
